name: Artifact Java Spring

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ['web/documentserver-example/java-spring/**']
  pull_request:
    branches: [master]
    paths: ['web/documentserver-example/java-spring/**']

jobs:
  artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Build Artifact
        run: |
          cd ${{ github.workspace }}
          cwd=$(pwd)
          git submodule update --init --recursive
          cd ./web/documentserver-example/java-spring
          mkdir -p ./deploy/'Java Spring Example'
          rsync -av --exclude='deploy' ./ ./deploy/'Java Spring Example'
          cd ./deploy/'Java Spring Example'/src/main/resources/assets
          rm -rf ./.git/
          rm .git
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Java.Spring.Example
          path: ${{ github.workspace }}/web/documentserver-example/java-spring/deploy